### ISSUE TITLE
Fails to render title with 5.9.0-beta.0

### ISSUE THREAD

**Issue by jakelandis** [elpnt/inkdrop-code-title#18]
After upgrading to Inkdrop 5.9.0-beta.0 the title's no longer appear in the rendered output.

<img width="212" alt="image" src="https://github.com/user-attachments/assets/0ceefebc-d67b-4ac4-8445-5b57b0fbadf3">

Markdown:
<img width="208" alt="image" src="https://github.com/user-attachments/assets/95536915-9972-4571-b18d-1356623e391d">

Rendered:
<img width="187" alt="image" src="https://github.com/user-attachments/assets/308cd1d5-8782-4cde-84ec-e74db7c612bd">

(btw, love this plugin!)

**Comment by elpnt** [comment]
@jakelandis sorry for too late response! @basyura san fixed the bug in #19 and I published the patched version.

**Comment by jakelandis** [comment]
thanks !  It works again. 

Not sure why, but it didn't work just after upgrading to v3.2.0. 

I had to upgrade, then disable
<img width="122" alt="image" src="https://github.com/user-attachments/assets/13d4c21d-83f2-44c6-a489-f394f5426ab8">
then re-enable 
<img width="127" alt="image" src="https://github.com/user-attachments/assets/c3399d0d-1e71-422a-b27f-62b61814996b">
now it works great!
